apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: email-microservice
  namespace: dwetter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email-microservice
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75