apiVersion: v1
kind: Service
metadata:
  name: email-microservice
  namespace: dwetter-develop
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: email-microservice
  type: ClusterIP
