name: Python push on develop branch

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: python:3.8-alpine
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Test with pytest
        run: |
          pytest
      
      - name: Upload scripts artifact
        uses: actions/upload-artifact@v1
        with:
          name: scripts-artifact
          path: ./scripts
      
      - name: Upload templates artifact
        uses: actions/upload-artifact@v1
        with:
          name: templates-artifact
          path: ./templates

      - name: Upload Dockerfile artifact
        uses: actions/upload-artifact@v1
        with:
          name: dockerfile-artifact
          path: ./Dockerfile

  deliver:
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Download scripts artifact
        uses: actions/download-artifact@v1
        with:
          name: scripts-artifact
          path: ./scripts