name: Python push on feature branch

on:
  push:
    branches: [feature/*]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: python:3.8-alpine
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      