name: Python push on feature branch

on:
  push:
    branches: [feature/*]

env:
  PROJECT_NAME: email_microservice

jobs:
  sonarcloud-scan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-22.04
    container:
      image: python:3.8-alpine
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            flake8 \
            pytest \
            pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Build and lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names.
          flake8 . \
            --count \
            --select=E9,F63,F7,F82 \
            --show-source \
            --statistics

          # --exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide.
          flake8 . \
            --count \
            --exit-zero \
            --max-complexity=10 \
            --max-line-length=127 \
            --statistics
      
      - name: Test with pytest and pytest-cov
        run: |
          pytest ${{ env.PROJECT_NAME }}/tests/tests.py \
            --doctest-modules \
            --junitxml=junit/test-results.xml \
            --cov=com \
            --cov-report=xml \
            --cov-report=html

      - name: Upload pytest results artifact
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-artifact
          path: junit/test-results.xml
